import PageLayout from '@/components/layout/PageLayout';
import BlogPostCard from '@/components/blog/BlogPostCard';
import { BlogPost } from '@/types';

const blogPosts: BlogPost[] = [
  {
    title: 'Liquor, Sweat, and Bulletproof Glass',
    subtitle: 'Embracing Identity',
    imageUrl: '/images/Dad.JPG',
    imagePosition: 'left',
    content: [
      "A mile east of where the 5 merges with the San Bernardino freeway is Duke's Sportsman Liquor store. Duke and Sunny, my middle aged parents from South Korea, owned the small liquor store in the city of Terrace for nearly a decade. Sitting on a stool behind the hanging rolls of scratchers, I watched my parents work. My dad, with his toes exposed in his velcro sandals, greeted customers while talking with the Budweiser courier about the day's shipment. My mother stood at the counter behind the bullet proof glass for hours on end, shifting her weight from one leg to the other to spare her aching muscles. Occasionally, a regular customer walked in and greeted me. \"Duke Junior\" is the title I was given as I had some of my father's strong Korean features: monolids and pronounced cheekbones. Around sunset, my mother and I left the store. As we reversed out of the parking lot, my father stood and waved goodbye. On the radio was 50 cent's \"In da Club\" and my mother left the windows of the Chevy wide open almost as if she was letting the wind evaporate the day's sweat.",
      "My parents eventually sold Duke's Sportsman Liquor Store and moved onto a larger business in 2005. Royalty Market, located in the heart of South Central LA on 62nd and San Pedro, was much different than Duke's liquor. The glass got thicker, the ailes grew larger, and the weekends were no longer spent as a spectator as I frequented Ace wholesale with my mother to pick up a variety of vegetables, sodas, dairy, and cigarettes. We were regulars at the wholesale. The workers gave my mother a suitable nickname: \"Royalty!\", but I retained my title as Duke Junior. With an increased workload, my parents placed a queen size bed in the storage attic to sleep overnight, while leaving my sister and me with my grandma back at home in the San Fernando Valley. This was the busiest and most dangerous period in my parents' lives. An altercation with a customer led to a black eye and missing front teeth for my father. It was a common sight to see red salonpas along the back of my father's neck or around my mother's forearms.",
      "Jug Jug Sports Bar and Restaurant in the San Fernando Valley was my parents' last business venture together. After three years of opening the restaurant, my parents divorced, and I lived with my mother and sister. As a middle schooler too consumed in my own dramatic friend groups, I spent time neither with my mother who worked full time as a social worker at a nursing home nor with my father who worked tirelessly at the Korean-American fusion bar. Senior year in highschool/freshman year in college was an essential period for both my father's restaurant and me. The restaurant, after serving customers for nearly 5 years, required a new food safety certificate, supplemented with a strict health inspection. Greasy fingers and sore wrists from scraping under the fryer or the stinging sensation in my nostrils from bleach was a common side effect of working full time at the restaurant. My father repeated himself quite often about how \"there's nothing to be embarrassed about working in a kitchen and washing dishes\". I responded with silence. Placing my phone on the dish rack and playing 2000s rap was my attempt at channeling the memory of my mother's hair sticking to her damp forehead, or the bulletproof glass from a decade prior. I was working in a much safer area in addition to making a decent wage of 3 cents per plate washed. Windows down and on the way to deposit my day's salary at 2AM, was a moment when I came closer to understanding my parents' sacrifice and devotion for the family.",
      "While my parents may both be apologetic for not being consistently present for much of my siblings and my childhood, their example enabled me to acknowledge the power of grit and persistence. It is a privilege to understand the value of hard work and recognize the struggle of my parents as many other Korean-American valley kids were never exposed to the idea of hardship. I made simple mistakes such as buying expensive shoes or following the latest fashion trends throughout college in attempt to hide my less privileged background. Little did I know that my parents' efforts would have been in vain if I were to fail to recognize the loss of authenticity when burying the origins of my identity.",
      "I am proud of achieving a closer resemblance to my parents."
    ]
  },
  {
    title: 'Did you eat yet?',
    subtitle: 'Agape(ἀγάπη) love',
    imageUrl: '/images/Golf.JPG',
    imagePosition: 'right',
    content: [
      "\"Why can't you be like white parents?\" As a seventh grader who just spent the weekend at Jacob's house, I heard a constant flow of \"I love you\" and \"I love you too\" throughout the day. I bicycled back home just in time for my mom's signature spaghetti and meatballs, and I sat fiddling with my chopsticks until I asked, \"Do you love me?\" My mother stayed quiet until she said, \"Don't ask me those kinds of questions\".",
      "Every Korean man loves to golf. As I watched my father practice chipping in the backyard lawn, I faced him and imitated his swing. My parents were ecstatic at the prospect of their son becoming a professional golfer, and they began pouring as much time and money as they could into my junior golf career. Dad brought home golf balls that he bought from the owner of the range that he frequented, while mom trespassed beyond our property fence to pick up the balls that flew over. Hole 11 at Knollwood Golf Course, a cramped par 3 with a sharp cart-path-roundabout, will forever be my most cherished part of the course. Distracted and with no belts in the golf cart, I flew out onto the cart path due to the g forces in the roundabout. After this incident, my father held my hand whenever we rode together.",
      "I returned home from UCSD and visited my father at the restaurant. He stuffed my face with the Galbi that he marinated especially for me. As I ate, he displayed a concerned look since he knew I wasn't eating enough at school. After dinner, he brought me back into the kitchen to give me a suitcase that he packed full of ramen and canned food. I loaded the suitcase into the car and waved goodbye when he called my name. Confidently, with his broken english, he told me, \"I Lub You\".",
      "In my last year at UCSD, I had a minor allergic reaction to some gatorade protein bars that I scoffed down. I was tutoring Nabiha, when I was having difficulty breathing and noticed hives forming at the base of my hairline. I rushed out of the library to find the nearest road for an ambulance to pick me up and notified my mother at 8pm via text that I was going to the hospital. When I was discharged at 10pm, she was at my dorm. As she hugged me, I noticed her damp hands and lower back. My mother, one of the least capable drivers, frantically drove 130 miles to ensure I was okay. Walking with me back to her car, my mother opens the trunk and hands me a duffel bag. It was packed with food.",
      "It's a common theme in Asian culture to show love through other ways than vocal expression. Often times, it's known that \"Did you eat yet?\" directly translates to \"I love you\" in asian cultures. It is undeniably difficult for Asian-Americans to come to terms with the idea of non-vocal reassurance of their parents' love. However, once we grasp the idea that love is communicated differently across cultures, we form an undying appreciation for our parents for showing us more love than just saying \"I love you\"."
    ]
  },
  {
    title: '막내 (magnae)',
    subtitle: 'Cultural Identity In Los Angeles',
    imageUrl: '/images/magnae.JPG',
    imagePosition: 'left',
    content: [
      "고구려(高句麗; Goguryeo) existed in the korean peninsula from the first to seventh century. In an overly patriotic fashion, my father named his kids after the dynasty. Ko(brother), Rea(sister), Narang(sister), and me. The name \"Narang\" is a combination of the words \"Nara Sarang\" which directly translates to \"love the land(nation)\". For most of my life, I grew up with Narang. We were born a year and a half apart from one another and Ko and Rea are my half siblings who are 7 and 8 years older respectively. Narang and I often traveled to Diamond bar with my father to visit Ko and Rea and without fail, we always visited chuck e cheese's. When I was in the second grade, Ko and Rea's mother had passed away and they moved in with our father, my mother, narang, and me.",
      "Our bond as siblings was unlike any other. My childhood after Ko and Rea moved in seemed to rush by as much of our time was spent in laughter and excitement. Ko and Rea were undoubtedly busy high school students, but they always found time for their younger siblings. It was an exhilarating feeling to share many of the same high school teachers as Ko. We shared much of the same interests in the sciences, while both sisters were enamoured in the arts. I had several paths laid out before me as I could follow the direction of three other siblings. Being the magnae(last born), it was my responsibility to learn from my siblings' mistakes and experiences. Although I am truly privileged to have three older siblings to show me the best possible path to pave for myself, my father seems to have a conflicting traditional sense of family dynamic that counters the idea of being the beneficiary of my siblings. Korean culture places most emphasis on the success of the first born daughter or first born son; to have a younger child surpass the accomplishments of older siblings is thought to \"throw off the balance\". It's a strange sense to have expectations to either be a carbon copy of an older sibling, or to be \"lesser\".",
      "The most important takeaway from this traditional hierarchical family dynamic is to understand its differences to American values. American families tend to dismiss the idea of favoritism regarding their children's successes, as success is thought to have a subjective definition. However, success possesses a much more concrete definition in Korean culture: wealth, or the possibility of a comfortable livelihood. In rural Korea, to place most investment on the first-born maximizes the probability of a quicker return. This idea to place most emphasis on the first child may have been an effective investment strategy in Goguryeo, but only creates unnecessary family drama in the Kim family today. It's commonplace for all of us to butt heads regarding who claims the throne of \"having their act together\"."
    ]
  },
  {
    title: 'Cans and Bottles',
    subtitle: 'How much a dollar cost?',
    imageUrl: '/images/me2.jpeg',
    imagePosition: 'right',
    content: [
      "My family always collected and recycled bottles. Visiting home from UCSD, I scrunched water bottles and packed them into my duffel bag since I did not have a car to go to a recycling center near campus. Once I got home, I drove my family's decade old Hyundai to pick up several bags that contained green soju bottles from my father's restaurant along with a basket full of bottles that piled up at my mother's house. I collected on average 20-30 dollars that covered the train cost to visit home. It was a strange moment at UCSD since my two closest friends did not possess the same mindset. Hannam and Justin were both from well off families that did not have recycling in their repertoire. Walking back to the apartment from the on campus market, we passed by a crushed Starbucks Mocha Can. Even whilst being with my best friends, I feared that if I were to pick up the crushed can, I would be labeled as a person who was less fortunate. Cans reap the most money at a recycling center at a whopping 10 cents, so I picked up the can the next morning while there was no one around to see. Much of my sophomore year was wasted in attempt to blend in with my peers who wore expensive clothes and followed Hypebeast trends. Now I see the irony in recycling bottles and cans to fund a $120 shoe purchase.",
      "I was a junior transfer at UC Berkeley when I decided to rush an Asian fraternity. At the end of rush week, there was an event that took me to Origin NightClub in San Francisco. While I was talking with the brothers in line, there were dollar bills scattered around the floor. I ignored the dollar bills in the same fashion that I ignored the crushed mocha can and doing so elicited much of the same feelings. I was embarrassed to pick up the dollars to preserve my reputation in front of the brothers.",
      "Mom always reminded me of how large a dollar can be despite social status. Although a dollar may be a seemingly insignificant amount, it holds most of its value in reminding me of humbler beginnings. A dollar reminds me to practice gratitude for the people and experiences that helped me grow. These instances also allow me to form an appreciation for people who aren't afraid of judgement and those who regularly practice humility. My mother would never pass by a dime on the floor and she owns a house. Why should I ignore a can when I own nothing?"
    ]
  },
  {
    title: 'Familiarity in the unfamiliar',
    subtitle: 'Closer than we think',
    imageUrl: '/images/me2.jpeg',
    imagePosition: 'left',
    content: [
      "\"Finding familiarity in the unfamiliar\" is a concept that is often discussed when people encounter new experiences, such as starting a new job or moving to a new place. For some, it is the ability to relate to their new surroundings and make it feel like home. For me, finding familiarity in the unfamiliar is all about connecting with people.",
      "When most people talk about finding familiarity in the unfamiliar, it can be during moments such as finding a new job, moving to another country, or learning something new. Finding familiarity in the unfamiliar lets people feel a sense of comfort, security, or even a sense of direction. For instance, when a person moves to a new country, they try to relate their experiences and knowledge of their home to the new place that they live. It helps them navigate further into their new place, and lets them feel that there really is not much difference between the two.",
      "To me, finding familiarity in the unfamiliar involves interacting with people. I find it most satisfying to connect with people by not seeing them as strangers. I try to draw parallels between that person and people in my life. By doing this, I feel like I have much more wholesome and thorough conversations and the ability to express myself as I am.",
      "I was driving to school and noticed that the tire pressure monitor alert had gone off. I got off the freeway and went to a nearby Costco to fill up the air. There was a woman in her 50s who was also trying to fill air in her tires at the air pump next to mine. It looked as if she was concerned and wanted some help from workers at the tire center, but all of them were too busy to assist her. I could have simply filled up my tires and been on my way, but I felt a sense of responsibility to ask her if she needed help. She reminded me of my own mother. She drove the same Lexus SUV and had the same expeditious walk that almost every Asian mom seems to have. When I asked her if she needed help, her face lit up and she asked me how much she should inflate her tires. I asked her to sit in her car and turn it on so she could navigate to the tire pressure menu. I also showed her the recommended fill pressure that is located on the side of her door. I taught her these things, in the same way I would teach my mom. I filled her four tires, and after I was done, she told me that her son was my age and that I reminded her of him. We saw familiarity in one another as total strangers. However, I felt that our interaction was much more meaningful and thorough than if I were to help her in the manner of teaching a stranger.",
      "I was riding my motorcycle around Berkeley. I had finished my classes for the week, so I had a few hours to ride up to Grizzly Peak. As I came down the mountain, I decided to ride around the downtown area of Berkeley for the ambiance. As I turned the corner to ride down Telegraph Avenue, I noticed a child looking at me and waving profusely. I saw him out of the corner of my eye, so I couldn't wave back in time. I decided to turn the corner again and make my way around to the one-way street that he was on. I rode up to him and gestured for him to come and rev the motorcycle. He was unsure at first, but then I remembered that I was wearing a black leather race suit with a black helmet, and I realized that I might look intimidating to a four or five-year-old. I raised my visor and showed a smile through my eyes. His grandpa was with him, holding his hand, and he gave his grandson reassurance and gestured for him to rev the motorcycle. The boy, who was no taller than the handlebars of the bike, reached up and twisted the throttle. He scared himself with how loud the motorcycle was, and his grandpa laughed as we shared a wholesome moment. The grandpa reached out his hand in the gesture of a high-five, so I held up my hand, and he grasped it. He did one of those Gordon Ramsay high-five handholds instead of a high-five. He came close and said, \"Thank you.\"",
      "Finding familiarity in the unfamiliar can be a rewarding experience, especially when it comes to connecting with others. By drawing parallels between strangers and people in my life, I can make meaningful connections that go beyond the surface level. My encounters with a woman filling air in her tires and a child waving at me while I was riding my motorcycle are perfect examples of how finding familiarity in the unfamiliar can lead to wholesome and memorable interactions. In a world where strangers are often viewed with suspicion and caution, finding familiarity in the unfamiliar is a refreshing reminder of the kindness that exists in people."
    ]
  }
];

export default function Blog() {
  return (
    <PageLayout title="theLemonSqueeze">
      {blogPosts.map((post, index) => (
        <BlogPostCard key={index} {...post} />
      ))}
    </PageLayout>
  );
} 